// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoFNzD8Z1c4D_SsFPUCsOOZoS5epgPQXI',
    appId: '1:591807886821:web:ef6ea3400c960b590feb0c',
    messagingSenderId: '591807886821',
    projectId: 'decora-d69f0',
    authDomain: 'decora-d69f0.firebaseapp.com',
    storageBucket: 'decora-d69f0.firebasestorage.app',
    measurementId: 'G-PYL5LLM6GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi4VOUbDqZ5KWfwt221eL_C0HWMvWzo7o',
    appId: '1:591807886821:android:e5e80c6cc9e65e640feb0c',
    messagingSenderId: '591807886821',
    projectId: 'decora-d69f0',
    storageBucket: 'decora-d69f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAarfEGpvQQr-QcvoqQ3j0tIi0l_GV4C8',
    appId: '1:591807886821:ios:b4e7ee1d784a38fc0feb0c',
    messagingSenderId: '591807886821',
    projectId: 'decora-d69f0',
    storageBucket: 'decora-d69f0.firebasestorage.app',
    iosBundleId: 'com.example.decoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAarfEGpvQQr-QcvoqQ3j0tIi0l_GV4C8',
    appId: '1:591807886821:ios:b4e7ee1d784a38fc0feb0c',
    messagingSenderId: '591807886821',
    projectId: 'decora-d69f0',
    storageBucket: 'decora-d69f0.firebasestorage.app',
    iosBundleId: 'com.example.decoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoFNzD8Z1c4D_SsFPUCsOOZoS5epgPQXI',
    appId: '1:591807886821:web:7b59bd4360e960d60feb0c',
    messagingSenderId: '591807886821',
    projectId: 'decora-d69f0',
    authDomain: 'decora-d69f0.firebaseapp.com',
    storageBucket: 'decora-d69f0.firebasestorage.app',
    measurementId: 'G-P1KV0GL3XH',
  );
}
